Yboichuk/lua/sdcard
and3rson/lilka pull request #11
Opened 2024-03-19 20:24 UTC by black-ghost-off

Add basic functions for read from files/write to files/remove files/rename files/list directions

2024-03-21 19:54 UTC, and3rson requested changes

2024-03-21 19:54 UTC, and3rson commented on firmware/keira/src/apps/lua/lualilka_sdcard.cpp
> +    {"open_file", lualilka_sdcard_open_file},
Суфікси `_file` в методах непотрібні: і так очевидно, що всі операції - над файлами. Краще просто `open`, `close`, `read`, `write`, `size`, `remove`, `rename`.

2024-03-21 19:54 UTC, and3rson commented on firmware/keira/src/apps/lua/lualilka_sdcard.cpp
> +    FILE* current_file_entrie = static_cast<FILE*>(lua_touserdata(L, 1));
entrie -> entry

2024-03-21 19:54 UTC, and3rson commented on firmware/keira/src/apps/lua/lualilka_sdcard.cpp
> +    fseek(current_file_entrie, 0, SEEK_SET); // seek back to beginning of file
Щоб уникнути випадкового скидання позиції в файлі, варто зберегри початковий результат `ftell` перед цими викликами, наприклад:

```cpp
    size_t initial = ftell(current_file_entry); // get initial offset
    fseek(current_file_entry, 0, SEEK_END); // seek to end of file
    size_t size = ftell(current_file_entry); // get current file offset
    fseek(current_file_entry, initial, SEEK_SET); // seek back to initial position
```

2024-03-21 19:54 UTC, and3rson commented on firmware/keira/src/apps/lua/lualilka_sdcard.cpp
> +    old_name = "/sd/" + old_name;
Краще не хардкодити префікс, бо це потім буде важче знайти (якщо буде якийсь рефакторінг), а використати `LILKA_SDROOT`.

2024-03-21 19:54 UTC, and3rson commented on firmware/keira/src/apps/lua/lualilka_sdcard.cpp
> +    char* buf = static_cast<char*>(malloc(maxBytes));
Щоб не робити `free` перед кожним return, краще використати `std::unique_ptr`, наприклад:

```diff
-    char* buf = static_cast<char*>(malloc(maxBytes));
+    char* buf = new char[maxBytes];
+    std::unique_ptr<char> bufPtr(buf);
```

...після цього не потрібно робити free, оскільки unique_ptr автоматично звільнить пам'ять, щойно вийде за межі області видимості.

2024-03-21 19:54 UTC, and3rson commented on firmware/keira/src/apps/lua/lualilka_sdcard.cpp
> +    lilka::Entry entries[32];
Тут варто використати `SDCard::getEntryCount`, див. приклад тут:

https://github.com/and3rson/lilka/blob/2ba477ed62e2de66eb30666d8a69d13333f5b030/firmware/keira/src/apps/launcher.cpp#L135-L144

2024-03-21 19:54 UTC, and3rson commented on firmware/keira/src/apps/lua/lualilka_sdcard.cpp
> +#include <csetjmp>
Цей інклуд тут не потрібний

2024-03-21 20:15 UTC, black-ghost-off commented on firmware/keira/src/apps/lua/lualilka_sdcard.cpp
> +    fseek(current_file_entrie, 0, SEEK_SET); // seek back to beginning of file
Це потрібно для вирахування розміру файла?

2024-03-22 18:40 UTC, black-ghost-off commented on firmware/keira/src/apps/lua/lualilka_sdcard.cpp
> +    lilka::Entry entries[32];
Конфлікт з останніми комітами, треба rebase main в цю вітку (WIP)

2024-03-25 14:47 UTC, merged