File manager rework
and3rson/lilka pull request #138
Opened 2024-12-21 00:56 UTC by frostmorn

File manager moved to separate file.
Using stat to determine file size(faster than open/fseek)
Summary info about file by C button.
Back by B button.
MD5 calculation

2024-12-22 16:08 UTC, alder requested changes

2024-12-22 16:08 UTC, alder commented on firmware/keira/src/apps/fmanager.cpp
> +            AppManager::getInstance()->runApp(new LilTrackerApp(path));
Для MOD потрібно запускати програвач (ModPlayerApp), а для LT – Лілтрекер.

2024-12-22 16:08 UTC, alder commented on firmware/keira/src/apps/fmanager.cpp
> +            //   lilka::serial_log("Trying to check stat for %s", lilka::fileutils.joinPath(currentPath, filename).c_str());
Закоментований код треба видалити 🙂

2024-12-22 16:08 UTC, alder commented on firmware/keira/src/apps/fmanager.cpp
> +    //   lilka::serial_log("Loaded %d entries in %d msec", dirContents.size(), loadEnd - loadBegin);
Якщо цей код потрібен під час дебагу і не хочеться його видаляти, то можна обернути його в #ifdef.

2024-12-22 16:08 UTC, alder commented on firmware/keira/src/apps/fmanager.cpp
> +    //lilka::serial_log("Sorted for %d msec", sortEnd - loadEnd);
Дивись вище про #ifdef.

2024-12-22 16:08 UTC, alder commented on firmware/keira/src/apps/fmanager.cpp
> +    //lilka::serial_log("Added to ui for %d msec", addEnd - sortEnd);
Дивись вище про #ifdef.

2024-12-22 16:08 UTC, alder commented on firmware/keira/src/apps/fmanager.h
> +    //void openFileWith(String &path);
Закоментований код.

2024-12-22 16:08 UTC, alder commented on firmware/keira/src/apps/launcher.cpp
> +        // else if (index == 1) {
Закоментований код.

2024-12-22 16:10 UTC, frostmorn commented on firmware/keira/src/apps/fmanager.cpp
> +    } else if (lowerCasedFileName.endsWith(".mod") || lowerCasedFileName.endsWith(".lt")) {
поправлю

2024-12-22 16:11 UTC, frostmorn commented on firmware/keira/src/apps/fmanager.h
> +    //void openFileWith(String &path);
залишив бо планую додати цю фічу

2024-12-22 16:20 UTC, frostmorn commented on firmware/keira/src/apps/fmanager.cpp
> +            //   lilka::serial_log("Trying to check stat for %s", lilka::fileutils.joinPath(currentPath, filename).c_str());
я розумію що можна обгорнути в #ifdef, просто очевидну проблуму з кількістю тексту це не вирішить, та і потім на один флаг компіляції більше, ну нахіба.
а так на випадок якщо щось зламається не потрібно буде писати ці частини заново. до того ж по ним можна побачити слабкі місця

2024-12-22 16:21 UTC, frostmorn commented on firmware/keira/src/apps/launcher.cpp
> +        // else if (index == 1) {
тут можна і прибрати

2024-12-22 16:21 UTC, alder commented on firmware/keira/src/apps/fmanager.h
> +    //void openFileWith(String &path);
@frostmorn можна додавати в таких випадках щось на кшталт // TODO, або // FIXME

2024-12-24 10:14 UTC, alder approved these changes

2024-12-24 10:14 UTC, merged