Global sound settings implemented and sound menu
and3rson/lilka pull request #143
Opened 2024-12-23 12:48 UTC by noisedsn

sdk: global sound settings implemented.
keira: global sound settings implemented and sound menu added.
doom: global sound settings implemented.

2024-12-24 12:36 UTC, black-ghost-off requested changes
CLang-format not passed, CPPCheck not passed, fix it

2024-12-24 13:27 UTC, noisedsn commented
Справедливо. Ще вчора я про cppcheck нічого не знав, а позавчора про clang-format. Наче пофіксав, в мене проходять обидва тести тепер.

2024-12-24 21:47 UTC, frostmorn commented on firmware/keira/src/apps/settings/sound.cpp
> +            lilka::MenuItem volumeItem;
немає причин постійно викликати getItem()\setItem() під час відмальовування menu.
пропоную зробити це один раз після menu.isFinished()

2024-12-24 21:47 UTC, frostmorn commented on firmware/keira/src/apps/settings/sound.h
> +class SonudConfigApp : public App {
Очевидно треба змінити Sonud  на Sound

2024-12-24 21:53 UTC, frostmorn commented on sdk/lib/lilka/src/lilka/audio.cpp
> +            lilka::audio.adjustVolume(&buf, 2, 16);
чому не передати сюди  ping+i і викинути memcpy та buf

2024-12-24 21:54 UTC, frostmorn commented on firmware/keira/src/apps/weather/weather.cpp
> +                canvas->print(String(wind, 1) + " км/год");
додаткові зміни бажано робити окремими пул реквестами

2024-12-24 21:57 UTC, frostmorn commented on sdk/lib/lilka/src/lilka/audio.h
> +    void updateSettings();
доречніше мабуть використати назву loadSettings

2024-12-25 08:14 UTC, frostmorn commented on firmware/keira/src/apps/settings/sound.cpp
> +        menu.getItem(index, &item);
припускаю тестував як це працює і забув видалити :)

2024-12-25 08:19 UTC, frostmorn commented on firmware/keira/src/apps/liltracker/liltracker.cpp
> +    sequencer.setMasterVolume(0.25f * lilka::audio.volumeLevel / 100);
в принципі це непогано.
зазвичай поля класу в яких знаходяться якісь дані які можуть змінюватися роблять приватними, 
і реалізують для них два методи, типу 
getVolume()
і 
setVolume()
на перспективу це дозволяє потім не шукати по всьому коду де саме volume змінюється, та дозволяє відносно швидко вирішити проблему читання\запису данних з різних потоків.
хоча це і майже неможливий сценарій в нашому випадку :)
тому дані зазвичай private

2024-12-25 08:21 UTC, frostmorn commented on firmware/keira/src/apps/settings/sound.cpp
> +    menu.addItem("Гучність:", 0, 0U, static_cast<String>(lilka::audio.volumeLevel));
можна просто String(lilka::audio.volumeLevel)

2024-12-25 08:23 UTC, noisedsn commented on firmware/keira/src/apps/settings/sound.cpp
> +        menu.getItem(index, &item);
Майже. Копіпастив з доки приклад і не все видалив :)

2024-12-25 08:30 UTC, frostmorn commented on firmware/keira/src/apps/settings/sound.cpp
> +    return;
це відбудеться саме по собі, return можна і не писати :)

взагалі, зазвичай return використовують для повернення якихось значень, або якщо хочеться вийти раніше ніж заплановано. тут ти вийдеш з функції в будь-якому випадку

2024-12-25 08:44 UTC, frostmorn commented on firmware/keira/src/apps/settings/sound.cpp
> +    lilka::audio.volumeLevel = prefs.getUInt("volumeLevel", 100);
в принципі, можна перенести startupSound, startupBuzzer і volumeLevel в приватні поля audio,
реалізувати для них публічні методи
bool isStartupSoundEnabled/setStartupSoundEnabled(bool)
bool isStartupBuzeerEnabled/setStartupSoundBuzeer(bool)
void setVolumeLevel(uint32_t)
uint32_t getVolumeLevel(uint32_t)

підгрузку початкових значень запхнути в audio.begin

2024-12-25 13:12 UTC, closed without merging