Fix buildage for lilka v1
and3rson/lilka pull request #46
Opened 2024-03-24 12:01 UTC by frostmorn

2024-03-24 15:17 UTC, and3rson requested changes

2024-03-24 15:17 UTC, and3rson commented on firmware/keira/src/apps/nes/osd.cpp
> +    return osd_init_sound();
Я б все рівно повертав тут 0, інакше емуль взагалі не буде запускатись, якщо звук не вдасться ініціалізувати

2024-03-24 15:17 UTC, and3rson commented on firmware/keira/src/apps/nes/osd.cpp
> +#if LILKA_VERSION == 1
Аналогічно треба додати #ifdef в `osd_setsound`, щоб не спавнити RTOS-таску для звуку.

І ще, цей код же буде викликаний на v1, навіщо саме таке формулювання? ("This part of code should never be called")

2024-03-24 17:17 UTC, frostmorn commented on firmware/keira/src/apps/nes/osd.cpp
> +#if LILKA_VERSION == 1
Аби дізнатись якщо він виконається що щось пішло не так

2024-03-24 17:21 UTC, and3rson commented on firmware/keira/src/apps/nes/osd.cpp
> +#if LILKA_VERSION == 1
А, окей, не додивився решту коду

2024-03-24 17:23 UTC, and3rson commented on firmware/keira/src/apps/nes/osd.cpp
> +#if LILKA_VERSION == 1
Хоча ні. osd_init_sound буде викликатись на всіх версіях, тому не треба ним фейлити запуск емулятора, якщо звуку немає

2024-03-24 17:23 UTC, frostmorn commented on firmware/keira/src/apps/nes/osd.cpp
> +#if LILKA_VERSION == 1
там взагалі не виконається той кусок бо я рубанув його так би мовити на корню ще в begin,
не бачу аби osd_setsound десь викликався

2024-03-24 17:35 UTC, frostmorn commented on firmware/keira/src/apps/nes/osd.cpp
> +    return osd_init_sound();
+

2024-03-25 15:41 UTC, and3rson submitted a review, later dismissed

2024-03-25 15:44 UTC, merged