not enough stack, let's use heap instead(sdBrowserMenu)
and3rson/lilka pull request #8
Opened 2024-03-17 22:41 UTC by frostmorn

Should work, but can't check :)

2024-03-18 23:20 UTC, and3rson requested changes
Дякую за PR! Декілька проблем:
- Змінна `File file` в sdcard.cpp:116 ініціалізується повторно всередині do {}. Це призводить до шедовінгу зовнішньої змінної, яка залишається неініціалізованою. Тому цикл виконується лише 1 раз.
- Пам'ять виділяється лише на _numEntries файлів, але їх потрібно _numEntries + 1 (ще є пункт "<< Назад")
- Замість new, можна ініціалізувати entries/filenames/etc в стеку:
    ```cpp
    lilka::Entry entries[_numEntries];
    ```
    Це спростить менеджмент пам'яті, і не потрібно буде слідкувати за всіма return-ами, щоб там зробити delete.
- Потрібно переформатувати код через clang-format (див. зафейлені перевірки)
- Я особисто б уникав `do {} while()` - як на мене, `while() {}` читабельніший. Але то не критично. :)
- Краще назвати метод `getEntryCount` - він натякає на отримання чогось

2024-03-18 23:22 UTC, and3rson commented on sdk/lib/lilka/src/lilka/sdcard.cpp
> +    File file;
Ось перша ініціалізація, а в рядку 112 - повторна (shadowing). Відповідно, в while використовується оця (яка залишається неініціалізованою)

2024-03-18 23:28 UTC, and3rson commented
Якщо хочеш використовувати саме купу замість стеку - то можна залишити new, але оскільки нещовдавно в menu з'явився метод `addItem` (і ці filenames/icons/colors - це залишок з старого коду меню), нам більше не потрібно виділяти пам'ять для іконок наперед, можна зробити щось таке:

```cpp
    lilka::Menu menu("SD: " + path); // Створюємо меню відразу
    lilka::Entry *entries = new lilka::Entry[_numEntries];
    int numEntries = lilka::sdcard.listDir(path, entries);
    String *filenames = new String[numEntries];
    for (int i = 0; i < numEntries; i++) {
        // Додаємо пункти на льоту, без виділення пам'яті для масивів назв/іконок/кольорів
        menu.addItem(
            entries[i].name, 
            entries[i].type == lilka::EntryType::ENT_DIRECTORY ? &folder : get_file_icon(filenames[i]),
            lilka::EntryType::ENT_DIRECTORY ? lilka::display.color565(255, 255, 200) : get_file_color(filenames[i])
        );
    }
    // Зразу звільняємо пам'ять:
    delete[] filenames;
    // Все чисто, Menu само звільнить свою пам'ять
```

2024-03-19 01:24 UTC, frostmorn commented
Там сама суть була якраз в тому що ми не можемо знати скільки файлів у директорії тому немає що і виділяти у стеку. Більше ніж 32 файли і воно гарантовано впаде. Повторної декларації змінної не помітив. :D та й таке

2024-03-19 02:17 UTC, frostmorn commented
не можу знайти в коді місце де оброблюється кнопка "<< Назад",  та і в entries вона аж ніяк не додається, скоріше за все в попередній реалізації в стеку в entries[numEntries-1].name буде якесь сміття яке й заставить повернутися назад через return в попередній нескінченний цикл while :)
тому здається так має бути краще

2024-03-19 14:18 UTC, and3rson commented
Значно краще!

Ще одне зауваження: оскільки там всякі break/return, в майбутньому може виникнути випадковий витік пам'яті. Замість явного delete можна додати std::unique_ptr, який автоматично очистить пам'ять:

```diff
     lilka::Entry* entries = new lilka::Entry[_numEntries];
+    std::unique_ptr<lilka::Entry[]> entriesPtr(entries);
// ...
-         delete[] entries;
// ...
-    delete[] entries;
```

2024-03-19 14:30 UTC, frostmorn commented
звісно це вже зовсім прискіпливо, хоча на одну стрічку кода менше, чому ні  =)

2024-03-19 19:24 UTC, and3rson commented
Затестив - все працює. Дякую!

2024-03-19 19:24 UTC, and3rson approved these changes

2024-03-19 19:25 UTC, merged