Single FileSystem class
and3rson/lilka pull request #84
Opened 2024-03-29 12:13 UTC by frostmorn

closes https://github.com/and3rson/lilka/issues/28

Still need to check some places on possible mistakes

2024-03-29 13:56 UTC, and3rson commented
Хороша ідея, але я все ж маю трохи критики щодо цього підходу.

Я згоден, що треба викинути `lilka::SD` і `lilka::SPIFFS`. Але абстракція `FileSystem`, як на мене, лише приховує та ускладнює вже існуючі `SD` і `SPIFFS` з arduino-фреймворку esp32.

Також я згоден, що добре мати "хелпер" `FileSystem` з методами типу `isXXXAvailable` / `mountXXX`, а також методи для конверсії шляхів між канонічними та відносними. Крім того, там можна залишити функцію `listDir`.

Проте стосовно решти функцій - чому б не використовати вже існуючі `SD` і `SPIFFS` (не наші, а з esp32)? В більшості випадків нам треба буде працювати з SD-шляхами, а канонічні шляхи потрібні лише для низькорівневих бібліотек чи портів (наприклад, nofrendo чи doom).

Тим паче, існуючі (ардуїнівські) SD і SPIFFS наслідують FS, тому з ним теж можна без проблем мати єдину функцію для браузера з сигнатурою `fileBrowser(FS* driver, String path)`. А для конверсії шляхів в абсолютні можна якраз додати методи в `FileSystem` (як я описав тут: https://github.com/and3rson/lilka/pull/15#discussion_r1534615046)

TL;DR: Я вважаю, що FileSystem не має бути проксі для SD та SPIFFS, а лише хелпером, що здіснює ініціалізацію носіїв та надає деякі методи для зручності (конверсія шляхів і лістінг директорій).

2024-03-30 12:58 UTC, and3rson commented
Виглядає супер! От тільки я б залишив `sdcard` в Lua як є, все-таки юзери переважно будуть працювати в ній лише з SD-картою. Але можна трохи змінити код, щоб замість `open(LILKA_SDROOT + path)` були `SD.open(path)`. Тоді ми пізніше зможемо зробити інші Lua-модулі для інших ФС

2024-03-31 22:55 UTC, and3rson requested changes
Кльово, мені це дуже подобається!

2024-03-31 22:55 UTC, and3rson commented on sdk/lib/lilka/src/lilka/fileutils.cpp
> +const String FileUtils::getRelativePath(const String& path) {
Думаю, є сенс повертати структуру, що містить драйвер і шлях, наприклад:

```cpp
typedef struct {
    FS* driver;
    String path;
} PathInfo;

const PathInfo FileUtils::getRelativePathInfo(const String& path) {
    if (...) {
        return { .driver = &SD, .path = path.substring(...) };
    }
    / ...
}
```

Якщо юзера буде цікавити лише шлях - він зможе робити `lilka::fileutils.getRelativePathInfo("/sd/foo").path`. Якщо і драйвер теж - то зможе робити `lilka::PathInfo info = lilka::fileutils.getRelativePathInfo("/sd/foo"); info.driver.open(info.path);`

2024-03-31 22:55 UTC, and3rson commented on sdk/lib/lilka/src/lilka/fileutils.h
> +    FileUtils();
Потрібно обов'язково додати (українські) докстрінги до всіх публічних методів - з них doxygen генерує доки для нашого readthedox. За зразок можеш взяти `display.h`. Якщо не хочеш - я можу дописати це сам. :)

> [!NOTE]
> FYI - Докстрінги мають починатись з потрійного слеша (`///`)

2024-03-31 22:55 UTC, and3rson commented on sdk/lib/lilka/src/lilka/fileutils.h
> +#define LILKA_SDROOT_LEN      3
`#define LILKA_SDROOT_LEN sizeof(LILKA_SDROOT) - 1` :)

2024-03-31 22:55 UTC, and3rson commented on sdk/lib/lilka/src/lilka/fileutils.h
> +#define LILKA_SPIFFS_ROOT     "/fs"
Користуючись нагодою, може перейменуємо це на `/spiffs`? :)

2024-03-31 22:55 UTC, and3rson commented on sdk/lib/lilka/src/lilka/fileutils.h
> +    FS* getFSysDriverByFullPath(const String& path);
Цей метод можна змерджити з `getRelativePath` (див. коментар до `getRelativePath`)

2024-03-31 22:55 UTC, and3rson commented on sdk/lib/lilka/src/lilka/fileutils.h
> +    size_t listDir(FS* fSysDriver, const String& path, Entry entries[]);
Було б дуже добре замість `path` називати аргументи `absPath` або `relPath` - це спрошує розуміння того, що потрібно передати методу ще до прочитання докстрінги

2024-03-31 22:55 UTC, and3rson commented on sdk/lib/lilka/src/lilka/fileutils.h
> +
Є пропозиція додати ще один метод: `joinPath(...)`. Він може спростити всі ці проблеми з трейлінг слешами

2024-04-01 04:14 UTC, frostmorn commented on sdk/lib/lilka/src/lilka/fileutils.h
> +#define LILKA_SDROOT_LEN      3
прибрав повністю, зробив частиною getRelativePathInfo

2024-04-01 06:03 UTC, frostmorn commented on sdk/lib/lilka/src/lilka/fileutils.h
> +    FileUtils();
з цим пунктом мабуть потрібна буде певна допомога :D

2024-04-03 19:11 UTC, and3rson requested changes
Дуже добре! Ми вже дууууже близько!

2024-04-03 19:11 UTC, and3rson commented on sdk/lib/lilka/src/lilka/fileutils.cpp
> +    return spiffsAvailable;
Замість додаткової змінної можна просто смикати `SPIFFS.begin()` - він повертає true, якщо FS вже  змонтовано (а якщо ні - намагається змонтувати, що теж ОК і є швидкою операцією)

2024-04-03 19:11 UTC, and3rson commented on sdk/lib/lilka/src/lilka/fileutils.cpp
> +const String FileUtils::getFullPath(const FS* fSysDriver, const String& relPath) {
Все ж раджу використати замість "full" термінологію "absolute" або "cannonical" - це менш двозначно для назви методів і при спілкуванні. Зокрема, в теже в `getRelativePathInfo` аргумент вже називається `absPath`, тому можна використовувати `absolute`.

Хоча особисто мені більше подобається термін "cannonical", оскільки він більш строгий, і він також є в докстрінгу. Наприклад, чисто технічно, шлях "/folder_inside_sdcard_root/file.txt` можна назвати *абсолютним* по відношенню до кореня SD-карти... А "канонічний" саме натякає, що це - "fully-qualified" шлях.

2024-04-03 19:11 UTC, and3rson commented on sdk/lib/lilka/src/lilka/fileutils.cpp
> +    sdMountLocked = true;
Отут варто еквайрити м'ютекс, про який я казав:
```diff
- sdMountLocked = true;
+ xSemaphoreTake(sdMutex, portMAX_DELAY);

+ // ОБОВ'ЯЗКОВО потрібно зробити xSemaphoreGive(sdMutex) перед КОЖНИМ return
```
(Звісно, `sdMutex` потрібно ініціалізувати в конструкторі: `sdMutex = xSemaphoreCreateMutex();`)

2024-04-03 19:11 UTC, and3rson commented on sdk/lib/lilka/src/lilka/fileutils.cpp
> +const String FileUtils::joinPath(const String& lPath, const String& rPath) {
Я мав на увазі метод з варіадичними аргументами, але... Коли подумав, що є купа нюансів з різним джойненням абсолютних і відносних шляхів - вирішив, що, можливо, він взагалі не потрібен - надто складно і надто багато edge-кейсів :)

2024-04-03 19:11 UTC, and3rson commented on firmware/keira/src/apps/launcher.cpp
> +            sdBrowserMenu(static_cast<FS*>(&SD), "/");
А навіщо cast? Хіба не компілиться без нього? SD і SPIFFS же наслідують FS

2024-04-03 20:47 UTC, frostmorn commented on sdk/lib/lilka/src/lilka/fileutils.cpp
> +const String FileUtils::joinPath(const String& lPath, const String& rPath) {
+ -
Залишив так як є, бо в принципі універсально

2024-04-03 20:57 UTC, frostmorn commented on firmware/keira/src/apps/launcher.cpp
> +            sdBrowserMenu(static_cast<FS*>(&SD), "/");
дурна звичка після с

2024-04-09 17:44 UTC, and3rson commented
Все супер, все працює!
Допишу трохи документації, внесу дрібні правки і можна буде мерджити. :)

2024-04-09 19:09 UTC, and3rson submitted a review, later dismissed

2024-04-09 19:16 UTC, merged

2024-04-09 19:17 UTC, and3rson commented
:tada: :tada: :tada: