WiFi: add minimal functional for wifi for lua scripts
and3rson/lilka pull request #9
Opened 2024-03-19 12:40 UTC by black-ghost-off

WiFi: add minimal functional for wifi for lua scripts, default like connect, disconnect, status and scan available neworks
(rssi, wifi_channel, encrypt type WIP)

2024-03-19 14:47 UTC, and3rson requested changes
Виглядає супер! Єдине зауваження - деякі функції містять `_controller_` замість `_wifi_` ;)

2024-03-19 17:44 UTC, yevhenboichuk commented
> Виглядає супер! Єдине зауваження - назви деяких функцій містять `_controller_` замість `_wifi_` ;)

Треба обережніше красти код з інших файлів))))

2024-03-19 18:28 UTC, black-ghost-off commented
Треба обережніше красти код з інших файлів))) І треба налаштувати свій акк)

2024-03-20 19:36 UTC, and3rson commented
@black-ghost-off там не співпадають назви в тестовій прозі і в коді. Я б радив всі методи в Lua називати lowercase (rssi, local_ip, etc)

2024-03-21 17:41 UTC, and3rson commented
LGTM!

2024-03-21 17:41 UTC, and3rson approved these changes

2024-03-21 17:42 UTC, merged